# Generated by Django 2.2.6 on 2019-10-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.CharField(default='https://1gr.cz/u/loga-n4/idnes.gif', max_length=200),
            preserve_default=False,
        ),
    ]
